name: Prar # bot name
description: thana # bot Description

globals:
  attributes: # static attributes
    - id: keys_v_out  #skill_id_attribute_id
      label: "Keys to Check"
      type: string[]
      value: ["w", "a", "s", "d", "space"]
      description: "Keys that the Keyboard Input node will monitor for presses"
